### ISSUE TITLE
The Jenkins Docker Plugin does not seem to work

### ISSUE THREAD

**Issue by philippefuentes** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#65] opened 2017-02-14 21:25 UTC
I followed this great tutorial to install jenkins on my k8s cluster (I'm new to jenkins), I could run jobs w/o any problem until I tried to use the Docker plugin to start docker container inside a job, for example:

```
stage "Prepare environment"
	docker.image('node:4.1.2').inside {
	    print "inside a node server"
	    sh("echo test");  
	    //sh("npm install");      
	  }
```

I get an error:

```
java.io.IOException: Failed to run image 'node:4.1.2'. Error: docker: Error response from daemon: mkdir /root/workspace: read-only file system.
```

here is the detailed log:
```
[Pipeline] stage (Prepare environment)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Prepare environment
Proceeding
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
+ docker inspect -f . node:4.1.2
.
[Pipeline] withDockerContainer
$ docker run -t -d -u 0:0 -w /root/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA -v /root/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:/root/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:rw -v /root/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:/root/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** --entrypoint cat node:4.1.2
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: Failed to run image 'node:4.1.2'. Error: docker: Error response from daemon: mkdir /root/workspace: read-only file system.
	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:125)
	at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Execution.start(WithContainerStep.java:175)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:184)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:18)
	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(jar:file:/var/jenkins_home/plugins/docker-workflow/WEB-INF/lib/docker-workflow.jar!/org/jenkinsci/plugins/docker/workflow/Docker.groovy:122)
	at org.jenkinsci.plugins.docker.workflow.Docker.node(jar:file:/var/jenkins_home/plugins/docker-workflow/WEB-INF/lib/docker-workflow.jar!/org/jenkinsci/plugins/docker/workflow/Docker.groovy:63)
	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(jar:file:/var/jenkins_home/plugins/docker-workflow/WEB-INF/lib/docker-workflow.jar!/org/jenkinsci/plugins/docker/workflow/Docker.groovy:116)
	at WorkflowScript.run(WorkflowScript:12)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:328)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:240)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:228)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE
```

For info the Kubernetes plugin is configured like this by the tuto.

![image](https://cloud.githubusercontent.com/assets/18396482/22949797/bcd19bf6-f303-11e6-97f4-41be84c49f76.png)
 

What can I do to be able to use the jenkins docker plugin ? I tried many things but no success, since I don't really know what I'm doing...

Thanks a lot

**Comment by viglesiasce** [comment] 2017-02-14 21:45
Hey there! I think this relates to #52 and while I'm not 100% sure of the solution I believe its due to the multiple levels of indirection of filesystems when running docker in docker. 

Can you try setting your working directory to `/` instead of `/root`?

**Comment by philippefuentes** [comment] 2017-02-14 22:40
Hi !, thanks for your answer,
Well, I also thought at the beginning that it was related but I was not sure anymore that it was also a docker plugin problem.

I tried what you suggested but it put all the jobs offline and blocked everything, had to trace the jenkins pod log:

```
INFO: Container is waiting jnlp-13d1c27e61818 [jnlp]: ContainerStateWaiting(message=runContainer: Error response from daemon: Invalid bind mount spec "/var/lib/kubelet/pods/feb0fae7-f304-11e6-ba47-42010a840096/volumes/kubernetes.io~empty-dir/workspace-volume:/": Invalid specification: destination can't be '/' in '/var/lib/kubelet/pods/feb0fae7-f304-11e6-ba47-42010a840096/volumes/kubernetes.io~empty-dir/workspace-volume:/', reason=RunContainerError, additionalProperties={})
```

**Comment by philippefuentes** [comment] 2017-02-14 23:05
To be totally exhaustif, when I tried to set the working directory to /home/jenkins (refering to #52 ), it seemed to go a little further in the pipeline process by reaching the "inside" block but it fails executing the sh "echo test":

```
[Pipeline] stage (Prepare environment)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Prepare environment
Proceeding
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
+ docker inspect -f . node:4.1.2
.
[Pipeline] withDockerContainer
$ docker run -t -d -u 0:0 -w /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA -v /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:/home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:rw -v /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:/home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** --entrypoint cat node:4.1.2
[Pipeline] {
[Pipeline] echo
inside a node server
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-fd5a0e1f/pid: Directory nonexistent
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-fd5a0e1f/jenkins-log.txt: Directory nonexistent
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-fd5a0e1f/jenkins-result.txt: Directory nonexistent
[Pipeline] }
$ docker stop --time=1 c62003a2be8f613c384eb53348adb171abfb77210d91c16220fdf07d1a0a060a
$ docker rm -f c62003a2be8f613c384eb53348adb171abfb77210d91c16220fdf07d1a0a060a
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code -2
Finished: FAILURE
```

Some other experiments, if I use this working dir "/toto/titi", I got:

```
java.io.IOException: Failed to run image 'node:4.1.2'. Error: docker: Error response from daemon: mkdir /toto: read-only file system.
```

If I use "/home/titi", I got the same as with "/home/jenkins":

```
[Pipeline] stage (Prepare environment)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Prepare environment
Proceeding
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
+ docker inspect -f . node:4.1.2
.
[Pipeline] withDockerContainer
$ docker run -t -d -u 0:0 -w /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA -v /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:/home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:rw -v /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:/home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** --entrypoint cat node:4.1.2
[Pipeline] {
[Pipeline] echo
inside a node server
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
sh: 1: cannot create /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-11a5c0ca/pid: Directory nonexistent
sh: 1: cannot create /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-11a5c0ca/jenkins-log.txt: Directory nonexistent
sh: 1: cannot create /home/titi/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-11a5c0ca/jenkins-result.txt: Directory nonexistent
[Pipeline] }
$ docker stop --time=1 951eebec0ede3f094d1c5d28ef0d975d46d8de5cbfa58c72efd29c1d576a0f5b
$ docker rm -f 951eebec0ede3f094d1c5d28ef0d975d46d8de5cbfa58c72efd29c1d576a0f5b
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code -2
Finished: FAILURE
```

leading me saying that only the /home dir is writable, but can't go any further with any subdir of /home. whatever it means...

**Comment by philippefuentes** [comment] 2017-02-15 00:19
I posted a question on stackoverflow here:
http://stackoverflow.com/questions/42238634/use-jenkins-docker-plugin-in-kubernetes-cluster-on-gke
Thanks for your time

**Comment by maxhawkins** [comment] 2017-03-03 16:15
I'm having this same problem now. Did you ever find a solution, @philippefuentes?

**Comment by philippefuentes** [comment] 2017-03-03 17:28
Unfortunately not...still waiting for a solution for this...

**Comment by viglesiasce** [comment] 2017-03-03 18:02
Hey folks!

Coming back around to this. I've been busy on other things but the core of the issue is that the directories have to exist at every level of the nested containment so configure all dirs in that way.

Is it possible to pass volumes to the Docker plugin? You need to essential say:

```
-v /root/workspace:/root/workspace
```

Remember that the executor is already running inside a container and the workspace is (by default) at `/root/workspace`. So you need to bind mount that workspace into your next container and have the docker plugin use that dir.

**Comment by maxhawkins** [comment] 2017-03-03 19:55
It turns out my issue was an unrelated configuration issue. I managed to figure it out. I didn't read the part in [the guide](https://cloud.google.com/solutions/jenkins-on-container-engine) about mounting /usr/bin/docker.

I hope the above solution works for you Philippe!

**Comment by philippefuentes** [comment] 2017-03-07 15:55
Hi guys, thanks for your inputs :)

@viglesiasce I checked to see if I can pass any volume to the docker plugin, but no success, don't see any option anywhere.
I tried to add it at a higher level in the global configuration (only place I found to add volumes) but it does not work there, as expected I guess:

![image](https://cloud.githubusercontent.com/assets/18396482/23664731/ac77ac92-0356-11e7-951e-6abd751147f3.png)

@maxhawkins I don't really see what your are referring to in the guide, can you be more specific ?

**Comment by maxhawkins** [comment] 2017-03-07 17:19
I was talking about [this subpage](https://cloud.google.com/solutions/configuring-jenkins-container-engine#configuring_the_build_executors) with the /usr/bin/docker volume mapping. It looks like you got that set up right.

I never had problems with the workspace permissions, only contacting the docker daemon. When I mapped the docker binary and socket I was able to run docker commands and everything worked.

**Comment by philippefuentes** [comment] 2017-03-07 17:39
Ok I see, in my case indeed this was already preconfigured by following this tuto.
To be sure we're talking about the same thing, I'm able to run docker commands in my script.
What I can't do is starting another container using the docker plugin syntax from inside my script.

Can you for example execute this code from a jenkinsfile in the multibranch pipeline job ?

````
docker.image('node:4.1.2').inside () {
  print "inside a node server"
  sh("echo test");
}
````

as a workaround for the moment, I installed the jenkins node plugin to be able to use node inside my jenkinsfile, but it would be great not having to install anything and start containers from a jenkinsfile.

**Comment by iglov** [comment] 2017-03-12 09:18
I think i have same problem.
pipeline
```
node {
    stage "Container Prep"
    // do the thing in the container
    docker.image('maven:3.3.3-jdk-8').inside {
        // get the codez
        stage 'Checkout'
        git url: 'https://github.com/damnhandy/Handy-URI-Templates.git'
        stage 'Build'
        // Do the build
        //sh "./mvnw clean install"
        sh "whoami"
        sh "id"
        sh "cat /etc/passwd"
        
    }
}
```
output
```
[Pipeline] node
Running on jenkins-slave-2 in /var/jenkins_home/workspace/docker-test
[Pipeline] {
[Pipeline] stage (Container Prep)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Container Prep
Proceeding
[Pipeline] sh
[docker-test] Running shell script
+ docker inspect -f . maven:3.3.3-jdk-8
.
[Pipeline] withDockerContainer
$ docker run -t -d -u 1001:1001 -w /var/jenkins_home/workspace/docker-test -v /var/jenkins_home/workspace/docker-test:/var/jenkins_home/workspace/docker-test:rw -v /var/jenkins_home/workspace/docker-test@tmp:/var/jenkins_home/workspace/docker-test@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** --entrypoint cat maven:3.3.3-jdk-8
[Pipeline] {
[Pipeline] stage (Checkout)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Checkout
Proceeding
[Pipeline] git
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/damnhandy/Handy-URI-Templates.git # timeout=10
Fetching upstream changes from https://github.com/damnhandy/Handy-URI-Templates.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/damnhandy/Handy-URI-Templates.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 9380caff2d46132c7e7a484c6aba02ac976642d0 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9380caff2d46132c7e7a484c6aba02ac976642d0
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master 9380caff2d46132c7e7a484c6aba02ac976642d0
 > git rev-list 9380caff2d46132c7e7a484c6aba02ac976642d0 # timeout=10
[Pipeline] stage (Build)
Using the ‘stage’ step without a block argument is deprecated
Entering stage Build
Proceeding
[Pipeline] sh
[docker-test] Running shell script
+ whoami
whoami: cannot find name for user ID 1001
[Pipeline] }
$ docker stop --time=1 7855fa17acd5dd71b5649be5d1e28b6d0c990953c58e044e469d779e86917842
$ docker rm -f 7855fa17acd5dd71b5649be5d1e28b6d0c990953c58e044e469d779e86917842
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```
In this case, docker run container with "docker run -t -d -u 1001:1001" where 1001 its user **Jenkins** in **host system**, but into container his dont know who is 1001. I think we must mount /etc/passwd in container "-v /etc/passwd:/etc/passwd:ro" but this way insecure. See https://github.com/docker/docker/issues/22323

**Comment by amitgilad3** [comment] 2017-03-19 09:01
unfortunately I have the same issue  , and was wondering if thier is any updates on the issue??
maybe i can help in some way?

**Comment by viglesiasce** [comment] 2017-03-20 17:04
Hey Folks,

Apologies that this did not come to me sooner but the approach here is wrong. What you should be doing is:

1. Create definitions for your pod templates that match the docker image to a Jenkins label
![pod template](https://cloud.google.com/solutions/images/jenkins-container-engine-kubernetes-pod-config.png)
2. Use that label in the node section to get a pod with that docker image
```
node ('debian-8') {
// do stuff
}
```

**Comment by philippefuentes** [comment] 2017-03-23 15:00
Thanks @viglesiasce ,  I tried this approach but I have an exception when I use another Pod Template, even referencing the same jenkins-k8s-slave image:

![image](https://cloud.githubusercontent.com/assets/18396482/24253634/1d672b3a-0fe1-11e7-9716-a4cd91f86543.png)

```
node ('nodejs') {
//my stuff
}
````
I get:

````
Started by user Philippe Fuentes
Replayed #103
 > git rev-parse --is-inside-work-tree # timeout=10
Setting origin to https://github.com/vetup/jenkins-test.git
 > git config remote.origin.url https://github.com/vetup/jenkins-test.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Accès organisation Vetup Github
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/*
Seen branch in repository origin/master
Seen 1 remote branch
Obtained Jenkinsfile from 33c5cc2a1c00e66ce1b17f92efd21c2e7c9527fc
[Pipeline] node
Running on default-c7fa966e79356 in /root/workspace/jenkins-test_master-X7X5Z54VVKXUA35MJKFUWRV7TO6FM63NQS24FG3FNTBT6FE67DVQ
[Pipeline] {
[Pipeline] sh
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: Failed to mkdirs: /root/workspace/jenkins-test_master-X7X5Z54VVKXUA35MJKFUWRV7TO6FM63NQS24FG3FNTBT6FE67DVQ
	at hudson.FilePath.mkdirs(FilePath.java:1169)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask$FileMonitoringController.<init>(FileMonitoringTask.java:112)
	at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:167)
	at org.jenkinsci.plugins.durabletask.BourneShellScript$ShellController.<init>(BourneShellScript.java:161)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:90)
	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:63)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:166)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:184)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)
	at WorkflowScript.run(WorkflowScript:10)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:74)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:165)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:328)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:240)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:228)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE

````

When I switch back in my script to the first initial template, everything is fine again:

```
node () {
//my stuff
}
````

Or
```
node ('k8s') {
//my stuff
}
````

**Comment by cilindrox** [comment] 2017-04-04 14:31
Running into the same issue here. 

If I set the working directory to `/root/workspace` and then mount a host volume from `/root/workspace` onto the jnlp slave's `/root/workspace` dir, then the kubernetes plugin fails to provision a new container, throwing a read-only file system error.

I've tried using the `home/jenkins` working directory, which throws a `Failed to write to /home/jenkins/.jenkins/cache/jars/**` error instead.

**Comment by viglesiasce** [comment] 2017-04-07 20:17
Closing this out as you can now configure the Kubernetes plugin in your pipelines:

https://github.com/jenkinsci/kubernetes-plugin#container-configuration

**Comment by robotmay** [comment] 2017-05-15 17:38
I think this issue should be reopened, as in its current state the tutorial for setting this up on GCE doesn't work. I am also having the same problem as mentioned in this thread, and like @philippefuentes I've tried pretty much everything I can think of. The closest I can get to success is having it error out with the workspace dir being on a read-only file system. I've tried dozens of different variations on the configuration but I've made no progress in a week of messing about with this.

Things I've tried:
* building docker inside the jnlp slave
* various jnlp slave images
* different workspace dirs
* binding/unbinding the docker binary and socket volumes
* binding a workspace volume

Being able to configure kubernetes in the pipelines hasn't helped in finding a working setup for this issue :(

**Comment by philippefuentes** [comment] 2017-05-15 18:39
Hi @robotmay , just in case you haven't read this, I recently created the issue #75 that is related I think, and it seems to be a good way to go, as defining additional podTemplate would allow to use custom slave images in the pipeline.
For now, the only podTemplate working is the default one created by this tutorial.
Meaning, to me, that a special configuration is applied through the predefined jenkins volume used to install Jenkins:
https://storage.googleapis.com/solutions-public-assets/jenkins-cd/jenkins-home-v3.tar.gz
that I cannot understand...

**Comment by viglesiasce** [comment] 2017-05-22 21:05
As noted in the other bug here is a pipeline that I got to work without issue:
```
podTemplate(label: 'ubuntu-k8s', containers: [
    containerTemplate(name: 'ubuntu', image: 'ubuntu:16.04', ttyEnabled: true, 
        command: 'cat')    
  ]) {
    node('ubuntu-k8s') {
        container('ubuntu') {
            stage('Run Command') {
                sh 'cat /etc/issue'
            }
        }
    }
}
```

Reopening until further feedback on this.

**Comment by bombela** [comment] 2017-08-15 00:49
the podTemplate seems to create a new template for every possible combination of images! This creates an unbounded list of pod templates for me. Is there is anyway to use podTemplate without storing it in jenkins' config?

**Comment by viglesiasce** [comment] 2017-09-19 20:05
@bombela this is not in the Jenkins config it is in your pipeline definition. Each repository can define its own.

Closing this issue as this is the path forward for per pipeline template config.

**Closed by viglesiasce** 2017-09-19 20:05 UTC

**Comment by dehypnosis** [comment] 2017-09-22 09:24
why closed again? seems not having definite solution yet..
I am with kubernetes and jenkins on same node of GKE

**Comment by dehypnosis** [comment] 2017-09-23 06:53
@philippefuentes hey guy, Did you ever find a solution? I wasted almost three days tyring to make it work. ㅠㅠ
