### ISSUE TITLE
Having trouble with running Docker images in Jenkins slaves

### ISSUE THREAD

**Issue by Chekote** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#52] opened 2016-11-03 23:35 UTC
Hi again!

So I'm making progress on my own build. The pipeline is working great and deploying my applications images just fine. But now I'm trying to compile certain project assets for the images and I'm running into issues.

For example, the project uses npm. In our environment, we don't use native installs of tooling, and instead run everything in Docker images. npm is no exception. The Docker images are working great in our dev environment, and our current CI environment (CircleCI), but whenever I try to run the following command in a stage of the Jenkinsfile:

```groovy
sh('npm install');
```

I get the following error in the build logs:

```
[nds_google_container_engine-NLXIZZR7ZURR4JJEWIOWTD36XE5QABL5DQH7Z73ZQIDCJJIU2IDQ] Running shell script
+ npm install
docker: Error response from daemon: mkdir /root/workspace: read-only file system.
```

I've ran some tests and it seems that the home folder (`/root`) in the Jenkins slaves is read only (the whole slave may be read-only). I'm assuming the Docker daemon is trying to create this workspace folder, but I'm honestly unfamiliar with it. I use Docker on Mac, and some of the inner workings are obscured by the way the Hypervisor is used on this platform.

Maybe this is related to the Jenkins Kubernetes Plugin?

Do you have any suggestions on what the problem / resolution might be? I'm continuing my research regardless, but I thought I'd ping you just incase you had some wisdom to share.

Thanks again for all your help!

**Comment by Chekote** [comment] 2016-11-04 00:08
So it looks like changing the "Jenkins slave root directory" of the Kubernetes Plugin from "/root/" to "/home/jenkins/" may have resolved the issue. Can you comment on whether or not this is a good idea?

**Comment by philippefuentes** [comment] 2017-02-14 14:08
Hi Chekote !
I'm having the same problem, I changed the root directory like you did but I can't run any shell script inside the container, when I try sh("node -v") for example, I have those errors:

I'm trying:

```
docker.image('node:4.1.2').inside {
    print "inside a node server"
    sh("echo test");        
  }
```

And I got:

```
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
+ docker inspect -f . node:4.1.2
.
[Pipeline] withDockerContainer
$ docker run -t -d -u 0:0 -w /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA -v /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:/home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA:rw -v /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:/home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp:rw -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** --entrypoint cat node:4.1.2
[Pipeline] {
[Pipeline] echo
inside a node server
[Pipeline] sh
[play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA] Running shell script
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-b3b5cf3e/pid: Directory nonexistent
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-b3b5cf3e/jenkins-log.txt: Directory nonexistent
sh: 1: cannot create /home/jenkins/workspace/play_PLR-437-jenkins-config-WQ5IB66PEGACJNE6UHFF54RVEEBWEEDWRSVCZM3YSVATI3UYUBXA@tmp/durable-b3b5cf3e/jenkins-result.txt: Directory nonexistent
[Pipeline] }
$ docker stop --time=1 e2da950dc015082a0490b97b1b976b3bc1a91f631800284e75df5cb475725e44
$ docker rm -f e2da950dc015082a0490b97b1b976b3bc1a91f631800284e75df5cb475725e44
[Pipeline] // withDockerContainer
```

Any idea ?
Thanks :)

**Comment by viglesiasce** [comment] 2017-05-22 21:06
Here is an example pipeline that works:

```
podTemplate(label: 'ubuntu-k8s', containers: [
    containerTemplate(name: 'ubuntu', image: 'ubuntu:16.04', ttyEnabled: true, 
        command: 'cat')    
  ]) {
    node('ubuntu-k8s') {
        container('ubuntu') {
            stage('Run Command') {
                sh 'cat /etc/issue'
            }
        }
    }
}
```

Closing this in favor of #65 .

**Closed by viglesiasce** 2017-05-22 21:06 UTC

**Comment by dehypnosis** [comment] 2017-09-22 08:58
why is this closed?
not work with kubernetes and jenkins in GKE now.

**Comment by dehypnosis** [comment] 2017-09-22 10:51
OMG..  why is this closed?
point is that `inside docker task` never works

**Comment by dehypnosis** [comment] 2017-09-23 15:38
gcr.io slave image is not ready for jenkins docker pipeline plugin

**Comment by Sermanes** [comment] 2018-11-06 10:40
> Hi again!
> 
> So I'm making progress on my own build. The pipeline is working great and deploying my applications images just fine. But now I'm trying to compile certain project assets for the images and I'm running into issues.
> 
> For example, the project uses npm. In our environment, we don't use native installs of tooling, and instead run everything in Docker images. npm is no exception. The Docker images are working great in our dev environment, and our current CI environment (CircleCI), but whenever I try to run the following command in a stage of the Jenkinsfile:
> 
> ```groovy
> sh('npm install');
> ```
> 
> I get the following error in the build logs:
> 
> ```
> [nds_google_container_engine-NLXIZZR7ZURR4JJEWIOWTD36XE5QABL5DQH7Z73ZQIDCJJIU2IDQ] Running shell script
> + npm install
> docker: Error response from daemon: mkdir /root/workspace: read-only file system.
> ```
> I've ran some tests and it seems that the home folder (`/root`) in the Jenkins slaves is read only (the whole slave may be read-only). I'm assuming the Docker daemon is trying to create this workspace folder, but I'm honestly unfamiliar with it. I use Docker on Mac, and some of the inner workings are obscured by the way the Hypervisor is used on this platform.
> 
> Maybe this is related to the Jenkins Kubernetes Plugin?
> 
> Do you have any suggestions on what the problem / resolution might be? I'm continuing my research regardless, but I thought I'd ping you just incase you had some wisdom to share.
> 
> Thanks again for all your help!

I know it's a very old issue, but if anyone wants to know a solution here I'll leave it:

The problem is that jenkins mounts the workdir folder as read only, if we want to raise a docker with a volume we will have to move our code to a folder like /home/jenkins/code and execute there the npm install or composer install etc... and exec docker run or docker-compose

**Comment by jondkelley** [comment] 2019-10-15 03:02
I don't know if you everyone gave up, but I've achieved a similar example pattern here. If someone can ping me if a similar pattern works using their Kubernetis plugin, I'd appreciate it. I might want this with Kubernetis some day. Bonus points if you share the kube pattern.


```
// start 2nd degree container
node('ecs-jnlp-agent') {
    stage("ecs 2nd degree container") {
        withEnv(
            [
                /* JENKINS INCEPTION is required to mount the ecs-ubuntu docker.sock, which mounts the ec2 bare metal
                   docker.sock from the ECS Task definition docker.sock - The 3rd degree introspection is required
                   in order to mount the build workspace from the 2nd degree ecs agent into the 3rd degree agent.
                   Confused yet? Welcome to I.N.C.E.P.T.I.O.N.

                   ec2 docker.sock (volume exports to ) -> ecs docker.sock (volume exports to) -> 3rd degree image
                */
                'DOCKER_SOCKET_INCEPTION=-v /var/run/docker.sock:/var/run/docker.sock', // INCEPTION the docker.sock
                // The variables below you may modify to fit your projects needs
                'GIT_REPO1_URL=https://github.com/YOUR_NAME/hello_world_shell.git', // git code
                'GIT_REPO1_BRANCH=master', //...............................// git this branch
                // 'GIT_REPO1_JENKINS_CREDENTIALS_ID=ffffffff-ffff-ffff-ffff-ffffffffffff', # an ssh key maybe
                'ANSI_BLUE=\033[00;34m', //................................// experiment with color inside 3rd docker
                'ANSI_RED=\033[00;31m', //.................................// experiment with color inside 3rd docker
                'ANSI_END=\033[0m', //.....................................// experiment with color inside 3rd docker
                'BUILD_IMAGE1=ubuntu:bionic', //...........................// use multiple build images, if you wanna
                'BUILD_IMAGE2=alpine', //..................................// use multiple build images, if you wanna
            ]
        )
        {
            // use a private registry with a credentials ID
            docker.withRegistry('https://docker.io', 'ffffffff-ffff-ffff-ffff-ffffffffffff') {
                // start 3rd degree container on the ECS cluster host of 2nd degree container
                docker.image("${env.BUILD_IMAGE1}").withRun("${env.DOCKER_SOCKET_INCEPTION}") {
                    ansiColor('xterm') {
                        stage("3rd degree ubuntu: set 1, do stuff") {
                            // git some code
                            git(
                                url: "${env.GIT_REPO1_URL}",
                                branch: "${env.GIT_REPO1_BRANCH}",
                                // credentialsId: "${env.GIT_REPO1_JENKINS_CREDENTIALS_ID}",
                            )
                            // run some shell
                            sh '''#!/usr/bin/env bash
                            echo -en "${ANSI_BLUE}"
                            bash echo_hello_world.sh
                            echo -en "${ANSI_END}"'''
                        }

                        stage("3rd degree ubuntu: set 2, say hello again") {
                            // shell again
                            sh '''#!/usr/bin/env bash
                            echo -en "${ANSI_RED}"
                            bash echo_hello_world.sh
                            echo -en "${ANSI_END}"'''
                        }
                    }
                }
                // start seperate 3rd degree container to build something else kind of different
                docker.image("${env.BUILD_IMAGE2}").withRun("${env.DOCKER_SOCKET_INCEPTION}") {
                    ansiColor('xterm') {
                        stage("3rd degree alpine: set 1") {
                            // git some code
                            git(
                                url: "${env.GIT_REPO1_URL}",
                                branch: "${env.GIT_REPO1_BRANCH}",
                                // credentialsId: "${env.GIT_REPO1_JENKINS_CREDENTIALS_ID}",
                            )
                            // run some shell
                            sh '''#!/usr/bin/env bash
                            echo -en "${ANSI_BLUE}"
                            bash hello.sh
                            echo -en "${ANSI_END}"'''

                            // 4th degree purgatory just to show off
                            docker.image("${env.BUILD_IMAGE2}").withRun("${env.DOCKER_SOCKET_INCEPTION}") {
                                ansiColor('xterm') {
                                    stage("4th degree alpine: purgatory") {
                                        sh '''#!/usr/bin/env bash
                                        echo -en "${ANSI_RED}"
                                        echo "You shouldn\'t be in here... the world is unstable here."
                                        echo -en "${ANSI_END}"'''
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}```
